### ISSUE TITLE
Make the bot work but not a mod

### ISSUE THREAD

**Issue by steinj13** [Andygmb/twitchy_the_bot#6]
Hey andy, steinj again, sorry for the nuisance. Is there any way to make the bot work without being a mod (giving it access to certain wiki pages or something)? We've tried but we get a praw error:

Traceback (most recent call last):
  File "/home/ubuntu/twitchy_the_bot/twitchy.py", line 220, in <module>
    livestreams.config.update_sidebar()
  File "/home/ubuntu/twitchy_the_bot/twitchy.py", line 115, in update_sidebar
    sidebar = self.r.get_settings(self.subreddit)
  File "/usr/local/lib/python2.7/dist-packages/praw-2.1.21-py2.7.egg/praw/decorators.py", line 331, in wrapped
    function.__name__, scope)
praw.errors.ModeratorOrScopeRequired: ```get_settings` requires a moderator of the subreddit or the OAuth2 scope `modconfig`` requires a moderator of the subreddit` requires a logged in session

**Comment by Andygmb** [comment]
The bot needs to be a moderator in order to edit the sidebar - you can reduce it's permissions in /about/moderator/ to only wiki, stylesheet and sidebar and it will work.
