### ISSUE TITLE
Wont launh

### ISSUE THREAD

**Issue by MattiSony** [Andygmb/twitchy_the_bot#8]
When I try to launch it I get this error:

    C:\Python27\twitchy_the_bot-master>python setup.py
      File "setup.py", line 19
        print "Invalid JSON in local file: default_wiki_config.json"
                                                               ^
    SyntaxError: Missing parentheses in call to 'print'

**Comment by Andygmb** [comment]
Could you paste your local default_wiki_config.json? Thanks.

**Comment by MattiSony** [comment]
I haven't changed anything in it but here:
```
{
		"max_streams_displayed":"12",
		"max_title_length":"50",
		"thumbnail_size":{
			"width":"80",
			"height":"50"
		},
		"stream_marker_start":"[](#startmarker)",
		"stream_marker_end":"[](#endmarker)",
		"string_format":"> 1. **[{name}](http://twitch.tv/{name})** - **{viewercount} Viewers**\n[{title}](http://twitch.tv/{name})\n",
		"no_streams_string":"**No streams are currently live.**\n",
		"wikipages":{
			"error_log":"twitchbot_error_log",
			"stream_list":"streams",
			"ban_list":"banned_streams"
		},
		"allowed_games":[],
		"messages":{
			"success":"Your stream will be added to the list of livestreams in the sidebar, it will display the next time you are live on twitch.tv.\n\nProblems? [Contact the moderators here](http://www.reddit.com/message/compose?to=%2Fr%2F{subreddit})\n\n Do not reply to this message.",
			"banned":"Sorry, but that stream is banned from this subreddit. If you feel this is an incorrect ban, [please message the moderators here](http://www.reddit.com/message/compose?to=%2Fr%2F{subreddit})\n\n Do not reply to this message.",
			"already_exists":"Your stream is already in the list of livestreams that this bot checks. If you have just messaged your stream, please wait 5-10 minutes for the sidebar to update.\n\n Problems? Contact the moderators [here](http://www.reddit.com/message/compose?            to=%2Fr%2F{subreddit})\n\n Do not reply to this message."
    		}
}
```

**Comment by Andygmb** [comment]
Oh derp, sorry - I should probably have read the SyntaxError (sorry, it's the morning).

The issue is you're presumably using python 3 when the bot uses python 2.7 syntax. Use a virtualenv with python 2.7.

I'll see what I can do to make it forward-compatible with py3.

**Comment by MattiSony** [comment]
I switched over to Python 2.7 and tried that but then I got this error

```
C:\Python27\twitchy_the_bot-master>python setup.py
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    import praw
ImportError: No module named praw
```

**Comment by Andygmb** [comment]
You'll need to do (assuming you have pip installed) 

    pip install praw

PRAW is the wrapper used to interact with reddits API and is a requirement of the bot.
